kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ include "core-keeper-dedicated.fullname" . }}-server-data"
  labels:
    {{- include "core-keeper-dedicated.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.serverData.size }}
  {{- if ne .Values.volumes.serverData.storageClass "" }}
  storageClassName: {{ .Values.volumes.serverData.storageClass }}
  {{- end }}
